# -*- coding: utf-8 -*-

from google.appengine.ext import db
#from google.appengine.api import users
'''
A model class describes a kind of entity.
'''



class Crisis(db.Model):
	# entity properties
	ID = db.StringProperty(required=True)
	name = db.StringProperty(required=True)
	history = db.TextProperty(required=True)
	help = db.TextProperty(required=True)
	resources = db.TextProperty(required=True)
	ctype = db.StringProperty(required=True)
	time = db.TextProperty(required=True)
	day = db.IntegerProperty(required=True)
	month = db.IntegerProperty(required=True)
	year = db.IntegerProperty(required=True)
	time_misc = db.TextProperty(required=True)
	city = db.StringProperty(required=True)
	region = db.StringProperty(required=True)
	country = db.StringProperty(required=True)
	deaths = db.IntegerProperty(required=True)
	displaced = db.IntegerProperty(required=True)
	injured = db.IntegerProperty(required=True)
	missing = db.IntegerProperty(required=True)
	himpact_misc = db.TextProperty(required=True)
	amount = db.IntegerProperty(required=True)
	currency =  db.StringProperty(required=True)
	eimpact_misc = db.TextProperty(required=True)
	pi_site = db.StringProperty(required=True)
	pi_title = db.StringProperty(required=True)
	pi_url = db.LinkProperty(required=True)
	pi_description = db.TextProperty()
	image_sites = db.ListProperty(item_type=str, required=True)
	image_titles = db.ListProperty(item_type=str, required=True)
	image_urls = db.ListProperty(item_type=db.Link, required=True)
	image_descriptions = db.ListProperty(item_type=db.Text, required=True)
	video_sites = db.ListProperty(item_type=str, required=True)
	video_titles = db.ListProperty(item_type=str, required=True)
	video_urls = db.ListProperty(item_type=db.Link, required=True)
	video_descriptions = db.ListProperty(item_type=db.Text, required=True)
	social_sites = db.ListProperty(item_type=str, required=True)
	social_titles = db.ListProperty(item_type=str, required=True)
	social_urls = db.ListProperty(item_type=db.Link, required=True)
	social_descriptions = db.ListProperty(item_type=db.Text, required=True)
	ext_sites = db.ListProperty(item_type=str, required=True)
	ext_titles = db.ListProperty(item_type=str, required=True)
	ext_urls = db.ListProperty(item_type=db.Link, required=True)
	ext_descriptions = db.ListProperty(item_type=db.Text, required=True)
	misc = db.TextProperty(required=True)
	orgs = db.ListProperty(item_type=db.Key, required=True)
	people = db.ListProperty(item_type=db.Key, required=True)

class Organization(db.Model):
	ID = db.StringProperty(required=True)
	name = db.StringProperty(required=True)
	history = db.TextProperty(required=True)
	phone = db.PhoneNumberProperty(required=True)
	email = db.EmailProperty(required=True)
	address = db.StringProperty(required=True, multiline=True)
	city = db.StringProperty(required=True)
	region = db.StringProperty(required=True)
	country = db.StringProperty(required=True)
	pi_site = db.StringProperty(required=True)
	pi_title = db.StringProperty(required=True)
	pi_url = db.LinkProperty(required=True)
	pi_description = db.TextProperty()
	image_sites = db.ListProperty(item_type=str, required=True)
	image_titles = db.ListProperty(item_type=str, required=True)
	image_urls = db.ListProperty(item_type=db.Link, required=True)
	image_descriptions = db.ListProperty(item_type=db.Text, required=True)
	video_sites = db.ListProperty(item_type=str, required=True)
	video_titles = db.ListProperty(item_type=str, required=True)
	video_urls = db.ListProperty(item_type=db.Link, required=True)
	video_descriptions = db.ListProperty(item_type=db.Text, required=True)
	social_sites = db.ListProperty(item_type=str, required=True)
	social_titles = db.ListProperty(item_type=str, required=True)
	social_urls = db.ListProperty(item_type=db.Link, required=True)
	social_descriptions = db.ListProperty(item_type=db.Text, required=True)
	ext_sites = db.ListProperty(item_type=str, required=True)
	ext_titles = db.ListProperty(item_type=str, required=True)
	ext_urls = db.ListProperty(item_type=db.Link, required=True)
	ext_descriptions = db.ListProperty(item_type=db.Text, required=True)
	misc = db.TextProperty(required=True)
	crises = db.ListProperty(item_type=db.Key, required=True)
	people = db.ListProperty(item_type=db.Key, required=True)

class Person(db.Model):
	ID = db.StringProperty(required=True)
	name = db.StringProperty(required=True)
	ptype = db.StringProperty(required=True)
	btime = db.TextProperty(required=True)
	bday = db.IntegerProperty(required=True)
	bmonth = db.IntegerProperty(required=True)
	byear = db.IntegerProperty(required=True)
	btime_misc = db.TextProperty(required=True)
	nationality = db.StringProperty(required=True)
	biography = db.TextProperty(required=True)
	pi_site = db.StringProperty(required=True)
	pi_title = db.StringProperty(required=True)
	pi_url = db.LinkProperty(required=True)
	pi_description = db.TextProperty()
	image_sites = db.ListProperty(item_type=str, required=True)
	image_titles = db.ListProperty(item_type=str, required=True)
	image_urls = db.ListProperty(item_type=db.Link, required=True)
	image_descriptions = db.ListProperty(item_type=db.Text, required=True)
	video_sites = db.ListProperty(item_type=str, required=True)
	video_titles = db.ListProperty(item_type=str, required=True)
	video_urls = db.ListProperty(item_type=db.Link, required=True)
	video_descriptions = db.ListProperty(item_type=db.Text, required=True)
	social_sites = db.ListProperty(item_type=str, required=True)
	social_titles = db.ListProperty(item_type=str, required=True)
	social_urls = db.ListProperty(item_type=db.Link, required=True)
	social_descriptions = db.ListProperty(item_type=db.Text, required=True)
	ext_sites = db.ListProperty(item_type=str, required=True)
	ext_titles = db.ListProperty(item_type=str, required=True)
	ext_urls = db.ListProperty(item_type=db.Link, required=True)
	ext_descriptions = db.ListProperty(item_type=db.Text, required=True)
	misc = db.TextProperty(required=True)
	crises = db.ListProperty(item_type=db.Key, required=True)
	orgs = db.ListProperty(item_type=db.Key, required=True)

class Ext(db.Model): #We'll add this in the future
	ext_sites = db.ListProperty(item_type=str, required=True)
	ext_titles = db.ListProperty(item_type=str, required=True)
	ext_urls = db.ListProperty(item_type=db.Link, required=True)
	ext_descriptions = db.ListProperty(item_type=db.Text, required=True)
